### ISSUE TITLE
Park the site behind CDN

### ISSUE THREAD

**Issue by alemsas** [HamedAp/x-ui-Persian#1]
Is there any way to use the same port? because I want to park my site behind CDN! and CDN has been limited by the port!

**Comment by HamedAp** [comment]
Yes you can add new remark and add new client .

**Comment by alemsas** [comment]
Also, I have another question!
after I turn on the cloud button on my site I have gotten a 502 error!do you have any idea about it?!

**Comment by HamedAp** [comment]
I don't know about that .
