### ISSUE TITLE
How to make a release

### ISSUE THREAD

**Issue by aligilani1986** [HamedAp/x-ui-Persian#5]
Hello dear Hamed

I need to fork and change some custom updates in x-UI.  But I don't know how to make a release in Linux and create an installer.
I'll be appreciated it if you help me

**Comment by mohkhz2001** [comment]
@aligilani1986 
did you find the way?

**Comment by HamedAp** [comment]
use github actions

**Comment by mohkhz2001** [comment]
@aligilani1986 you just need to install golang and in your terminal use `go build` command
